"""Run the sample queries against the live pipeline and write docs/sample_outputs.md.
Usage: python -m scripts.run_samples
"""
from pathlib import Path

from app.rag_graph import get_graph

QUERIES = [
    "What is Agentic AI and how does it differ from traditional or generative AI?",
    "What are the core components or capabilities of an AI agent?",
    "What benefits can enterprises expect from adopting Agentic AI?",
    "What challenges, risks or governance concerns does the eBook mention?",
    "Which industries or use cases does the eBook discuss for Agentic AI?",
    "What is the capital of France?",  # out-of-scope: must be refused
]

out = ["# Sample outputs (generated by scripts/run_samples.py)\n"]
graph = get_graph()
for i, q in enumerate(QUERIES, 1):
    r = graph.invoke({"question": q, "top_k": 5})
    out.append(f"## {i}. {q}\n")
    out.append(f"**Answer:** {r['answer']}\n")
    out.append(f"- answered: `{r['answered']}` | grounded: `{r['grounded']}` | confidence: `{r['confidence']}` "
               f"| retrieval_score: `{round(r['retrieval_score'], 4)}`")
    out.append(f"- reason: {r['reason']}")
    out.append("- retrieved: " + ", ".join(f"p{c['page']} ({c['score']})" for c in r["contexts"]) + "\n")
    print(f"[{i}/{len(QUERIES)}] done")

Path("docs/sample_outputs.md").write_text("\n".join(out), encoding="utf-8")
print("Wrote docs/sample_outputs.md")
